sentrydb:
  image: createdigitalspb/postgresql94:1.3
  env_file:
   - ./private/sentrydb.env
  volumes_from:
   - sentrydbdata

sentrydbdata:
 image: busybox
 volumes:
 - /data


sentry:
  image: createdigitalspb/sentry:1.0
  ports:
   - "49900:9000"
  links:
   - sentrydb:db
  volumes:
   - ./src:/project/src
  env_file:
   - ./private/sentrydb.env
   - ./private/sentry.env
