sentrydb:
  image: createdigitalspb/postgresql94:1.3
  env_file:
   - ./private/sentrydb.env
  volumes_from:
   - sentrydbdata

sentrydbdata:
 image: busybox
 volumes:
 - /data

redis:
  image: createdigitalspb/redis3:1.0-1-ga19d314
  expose:
    - "6379"


sentry:
  build: .
  ports:
   - "49900:9000"
  links:
   - sentrydb:db
   - redis:redis
  volumes:
   - ./src:/project/src
  env_file:
   - ./private/sentrydb.env
   - ./private/sentry.env
   - ./private/aws.env
